name: ${pluginName}
version: ${project.version}
main: ${package}.${mainClass}
author: ${author}
description: ${description}
api-version: "1.13"
load: POSTWORLD
softdepend:
#if ($useVault == "true")
- Vault
#end
commands:
permissions: